- name: Deploy the application stack to a server
  hosts: all
  remote_user: root

  vars_files:
   - "vars/secrets.yml"
   - "vars/values.yml"

  roles:
    - docker
    - traefik
    - prometheus
    - grafana
    - communitybot