- name: Set up RE Discord Community Host Environment
  hosts: localhost

  environment:
    DO_API_TOKEN: "c4dcebb3b54d6eba9e83e814cf596466aaa13da84f4f9977891ca1df11bd80c7"

  tasks:
    - name: Add SSH key
      digital_ocean_sshkey:
        name: "CatButtes SSH Public Key"
        ssh_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6/kE22FMkGXOFQu5MY6IpTfDiL55o7RBTkBObprPXpXI5vepHugqFPExv0x/jU+NEITB4lD7/GF5eobjPcv0jeZZgPsgWLln3QqRaFmLc8p3kQGgh5GTEEsmH+exuSDYZtOi1fJBtYRQ9roTfF/AunwR9O4HaCuwO4DwSnenXQl2lbhl7O7wp/RU+aCDOo9aT86mHci8/UmNe2AGxEIVC38VpfhhaxNtQ2cgBpvtWDyNUbVQDVw+Az8T7UTqMRQVKOjwL9ppilh24gkeT/L+7SSemhC0ZEOpa4HI6MTto8mL0/Cm6TPgO6F2aUl0jTdpZJG+F/qWLvC8cuhnPSl8/ catbuttes@outlook.com"
        state: present

    - name: Spin up VPS
      digital_ocean_droplet:
        name: "re-hosting-box"
        unique_name: yes
        ipv6: yes
        region: "ams3"
        image: "ubuntu-20-04-x64"
        size: "s-1vcpu-1gb"
        ssh_keys: 
          - "00:4f:c2:c8:ac:93:89:2c:63:31:17:53:6c:d7:0c:de"
        state: present
      register: re_droplet
    
    - debug:
        msg: "ID is {{ re_droplet.data.droplet.id }}, IP is {{ re_droplet.data.ip_address }}"

    - name: Tag resources as "re-discord"
      digital_ocean_tag:
        name: "re-discord" 
        resource_id: "{{ re_droplet.data.droplet.id }}" 
        state: present

    - name: Tag resources as "docker"
      digital_ocean_tag:
        name: "docker" 
        resource_id: "{{ re_droplet.data.droplet.id }}" 
        state: present 


