- name: Add SSH key
  digital_ocean_sshkey:
    name: "CatButtes SSH Public Key"
    oauth_token: "{{ DO_API_TOKEN }}"
    ssh_pub_key: "{{ ssh_public_key }}"
    state: present

- name: Spin up droplet
  digital_ocean_droplet:
    name: "{{ server_hostname }}"
    unique_name: yes
    ipv6: yes
    region: "ams3"
    image: "ubuntu-20-04-x64"
    size: "s-1vcpu-1gb"
    ssh_keys: "{{ ssh_key_fingerprint }}"
    state: present
    oauth_token: "{{ DO_API_TOKEN }}"
  register: re_droplet
    
- name: Tag resources
  digital_ocean_tag:
    name: "{{ item }}" 
    oauth_token: "{{ DO_API_TOKEN }}"
    resource_id: "{{ re_droplet.data.droplet.id }}" 
    state: present
  loop: "{{ server_tags }}"
  when: re_droplet is changed

- name: Create DNS A record to point to the box
  cloudflare_dns:
    zone: buttes.xyz
    record: "{{ server_hostname }}"
    type: A
    value: "{{ re_droplet.data.ip_address }}" 
    account_email: "{{ CLOUDFLARE_EMAIL}}"
    account_api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    state: present
  register: record
  when: re_droplet is changed

- name: Create DNS A record to point to the box
  cloudflare_dns:
    zone: buttes.xyz
    record: "{{ server_hostname }}"
    type: AAAA
    value: "{{ re_droplet.data.ipv6_address }}" 
    account_email: "{{ CLOUDFLARE_EMAIL}}"
    account_api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    state: present
  register: record
  when: re_droplet is changed
