
- name: Create DNS A record to point to the box
  cloudflare_dns:
    zone: buttes.xyz
    record: "{{ server_hostname }}"
    type: A
    value: "{{ re_droplet.data.ip_address }}" 
    account_email: "{{ CLOUDFLARE_EMAIL}}"
    account_api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    state: present
  register: record
  when: re_droplet is changed

- name: Create DNS AAAA record to point to the box
  cloudflare_dns:
    zone: buttes.xyz
    record: "{{ server_hostname }}"
    type: AAAA
    value: "{{ re_droplet.data.ipv6_address }}" 
    account_email: "{{ CLOUDFLARE_EMAIL}}"
    account_api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    state: present
  register: record
  when: re_droplet is changed